/* PocketVault Admin — Referral System */
const ReferralAdmin=(()=>{
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mwk=n=>`MWK ${Number(n||0).toLocaleString('en-MW')}`;
const headers=()=>({'Content-Type':'application/json','x-admin-secret':sessionStorage.getItem('pv_admin_secret')||''});
async function getOverview(){const r=await fetch('/api/admin/referrals/overview',{headers:headers()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
async function load(){const root=document.getElementById('referrals-page');if(!root)return;root.innerHTML='<div class="ref-loading">Loading referral system…</div>';try{render(root,await getOverview());}catch(e){root.innerHTML=`<div class="ref-error"><strong>Referral system unavailable</strong><p>${esc(e.message)}</p><button class="btn" onclick="ReferralAdmin.load()">Retry</button></div>`;}}
function render(root,d={}){const p=d.pool||{},s=d.stats||{},rows=Array.isArray(d.referrals)?d.referrals:[];root.innerHTML=`<div class="ref-header"><div><h1>Referral system</h1><p>Referral funding, rewards and participant tracking.</p></div><div class="ref-status ${d.enabled===false?'paused':''}">${d.enabled===false?'Paused':'Active'}</div></div><section class="ref-kpis"><div class="ref-kpi"><span>Referral pool</span><strong>${mwk(p.availableBalance)}</strong></div><div class="ref-kpi"><span>Total funded</span><strong>${mwk(p.totalFunded)}</strong></div><div class="ref-kpi"><span>Rewards paid</span><strong>${mwk(p.totalPaid)}</strong></div><div class="ref-kpi"><span>Pending rewards</span><strong>${mwk(p.pendingRewards)}</strong></div></section><section class="ref-panel"><div class="ref-panel-head"><div><h2>Fund referral pool</h2><p>Move approved funds into the dedicated referral balance.</p></div></div><div class="ref-transfer-grid"><form onsubmit="return ReferralAdmin.transfer(event,'main_pool')"><label>From Main Pool</label><div class="ref-inline"><input class="input" name="amount" type="number" min="1" step="1" placeholder="Amount in MWK" required><button class="btn btn-primary">Transfer</button></div></form><form onsubmit="return ReferralAdmin.transfer(event,'airtel')"><label>From Airtel account</label><div class="ref-inline"><input class="input" name="amount" type="number" min="1" step="1" placeholder="Amount in MWK" required><input class="input" name="reference" placeholder="Confirmed Airtel reference" required><button class="btn btn-primary">Record funding</button></div></form></div></section><section class="ref-panel"><div class="ref-panel-head"><div><h2>Referral participants</h2><p>${Number(s.totalParticipants||rows.length).toLocaleString()} tracked participants and relationships.</p></div><input class="input ref-search" placeholder="Search referrals" oninput="ReferralAdmin.filter(this.value)"></div><div class="ref-table-wrap"><table class="ref-table"><thead><tr><th>Referrer</th><th>Referred user</th><th>KYC</th><th>First save</th><th>Eligibility</th><th>Reward</th><th>Status</th><th>Action</th></tr></thead><tbody id="referral-rows">${rows.map(renderRow).join('')||'<tr><td colspan="8" class="ref-empty">No referral records yet.</td></tr>'}</tbody></table></div></section><section class="ref-panel"><div class="ref-panel-head"><div><h2>Pool controls</h2><p>Accounting and reward configuration.</p></div></div><div class="ref-ledger"><div><span>Pool status</span><strong>${esc(p.status||'active')}</strong></div><div><span>Reward per qualified referral</span><strong>${mwk(d.settings?.rewardAmount||500)}</strong></div><div><span>Program participants</span><strong>${Number(s.totalParticipants||0).toLocaleString()}</strong></div></div></section>`;}
function renderRow(r){const canPay=r.eligible&&String(r.rewardStatus||'').toLowerCase()!=='paid';return `<tr data-search="${esc([r.referrerName,r.referredName,r.referrerEmail,r.referredEmail].join(' ').toLowerCase())}"><td>${esc(r.referrerName||r.referrerEmail||'—')}</td><td>${esc(r.referredName||r.referredEmail||'—')}</td><td>${esc(r.kycStatus||'pending')}</td><td>${r.firstSave?'Confirmed':'Pending'}</td><td>${r.eligible?'Eligible':'Not eligible'}</td><td>${mwk(r.rewardAmount)}</td><td>${esc(r.rewardStatus||'pending')}</td><td>${canPay?`<button class="btn btn-primary btn-sm" onclick="ReferralAdmin.pay('${esc(r.id)}')">Pay</button>`:r.flagged?'<span class="ref-flag">Review</span>':'—'}</td></tr>`;}
function filter(q){const n=String(q||'').toLowerCase().trim();document.querySelectorAll('#referral-rows tr').forEach(row=>row.hidden=Boolean(n&&!(row.dataset.search||'').includes(n)));}
async function transfer(e,source){e.preventDefault();const form=e.currentTarget,amount=Number(form.amount.value),reference=form.reference?.value?.trim()||'';if(!Number.isInteger(amount)||amount<=0)return false;if(source==='airtel'&&!reference)return false;try{const r=await fetch('/api/admin/referrals/pool/fund',{method:'POST',headers:{...headers(),'Idempotency-Key':`ref-${source}-${reference||amount}`},body:JSON.stringify({source,amount,reference})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);alert('Referral pool funding recorded.');form.reset();load();}catch(err){alert(err.message);}return false;}
async function pay(id){if(!confirm('Pay the two MWK500 referral bonuses from the Referral Pool?'))return;try{const r=await fetch(`/api/admin/referrals/${encodeURIComponent(id)}/reward`,{method:'POST',headers:headers()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);alert(d.alreadyPaid?'Reward was already paid.':`Paid ${mwk(d.paid)} total.`);load();}catch(e){alert(e.message);}}
async function addOverviewCard(){const main=document.getElementById('main-content');if(!main||currentPage!=='overview'||document.getElementById('referral-pool-overview'))return;try{const d=await getOverview(),p=d.pool||{};const wrap=document.createElement('div');wrap.id='referral-pool-overview';wrap.className='ref-overview-card';wrap.innerHTML=`<div><span>Referral Pool</span><strong>${mwk(p.availableBalance)}</strong></div><button class="btn btn-outline btn-sm" onclick="navigate('referrals')">Open referral system</button>`;main.prepend(wrap);}catch{}}
return{load,filter,transfer,pay,addOverviewCard};})();
(function wireReferralAdmin(){const originalNavigate=window.navigate;window.navigate=async function(page,param){if(page==='referrals'){currentPage='referrals';document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page==='referrals'));const main=document.getElementById('main-content');if(main){main.innerHTML='<div id="referrals-page"></div>';await ReferralAdmin.load();}return;}const result=await originalNavigate(page,param);if(page==='overview')ReferralAdmin.addOverviewCard();return result;};const nav=document.querySelector('.sidebar-nav');if(nav&&!nav.querySelector('[data-page="referrals"]')){const item=document.createElement('div');item.className='nav-item';item.dataset.page='referrals';item.innerHTML='<span class="nav-icon">R</span><span>Referrals</span>';item.addEventListener('click',()=>window.navigate('referrals'));nav.appendChild(item);}if(typeof currentPage!=='undefined'&&currentPage==='overview')setTimeout(()=>ReferralAdmin.addOverviewCard(),250);})();
