(function(){'use strict';
const api=(path,method='GET',body)=>{const secret=sessionStorage.getItem('pv_admin_secret');return fetch(path,{method,headers:{'Content-Type':'application/json',...(secret?{'x-admin-secret':secret}:{})},body:body?JSON.stringify(body):undefined}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;});};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function load(){const root=document.getElementById('second-me-page');if(!root)return;root.innerHTML='<div class="loading-row"><span class="spinner"></span> Loading Second Me...</div>';try{const s=await api('/api/admin/second-me/status');root.innerHTML=`<div class="page-hdr"><div class="page-hdr-left"><h2>Second Me</h2><p>Internal support and operations assistant. It watches incidents, helps review support and prepares operating reports.</p></div></div><div class="stat-grid second-me-stats"><div class="stat-card"><div class="stat-icon">AI</div><div class="stat-label">AI Provider</div><div class="stat-value">${esc(s.provider||'Not configured')}</div><div class="stat-footer">${s.configured?'Ready':'Needs an API key'}</div></div><div class="stat-card"><div class="stat-icon">@</div><div class="stat-label">Founder Email</div><div class="stat-value">${s.emailConfigured?'Configured':'Not configured'}</div><div class="stat-footer">Attention alerts and reports</div></div><div class="stat-card"><div class="stat-icon">OP</div><div class="stat-label">Role</div><div class="stat-value">Operations</div><div class="stat-footer">Read-only by default</div></div></div><div class="second-me-grid"><section class="panel second-me-panel"><div class="panel-head"><div><h2>Attention Monitor</h2><p>Review new system errors and unresolved operational alerts.</p></div></div><button class="btn btn-primary" id="second-me-scan">Run attention scan</button><div id="second-me-scan-result" class="result-box" hidden></div></section><section class="panel second-me-panel"><div class="panel-head"><div><h2>Monthly Report</h2><p>Generate the founder-facing operating narrative from the existing financial report.</p></div></div><div class="form-grid"><label>Year<input id="second-me-year" class="input" type="number" value="${new Date().getFullYear()}"></label><label>Month<input id="second-me-month" class="input" type="number" min="1" max="12" value="${new Date().getMonth()+1}"></label></div><div class="second-me-actions"><button class="btn btn-outline" id="second-me-preview">Preview report</button><button class="btn btn-primary" id="second-me-send">Write & email report</button></div><div id="second-me-report" class="result-box" hidden></div></section></div><section class="panel second-me-panel"><div class="panel-head"><div><h2>Operating Rules</h2><p>How Second Me is allowed to work.</p></div></div><div class="rule-list"><div><strong>Read-only by default</strong><span>It can analyse and recommend, but it does not move money or change accounts.</span></div><div><strong>Evidence first</strong><span>It uses PocketVault records supplied to it and must not invent missing facts.</span></div><div><strong>Human escalation</strong><span>Issues involving money movement, identity, disputes, refunds or account changes require human review.</span></div></div></section>`;wire();}catch(e){root.innerHTML=`<div class="empty-state"><p>${esc(e.message)}</p></div>`;}}
function showResult(el,text){el.hidden=false;el.textContent=text;}
function wire(){document.getElementById('second-me-scan').onclick=async()=>{const b=document.getElementById('second-me-scan'),out=document.getElementById('second-me-scan-result');b.disabled=true;try{const r=await api('/api/admin/second-me/scan','POST',{});showResult(out,`Checked ${r.checkedErrors||0} errors and ${r.checkedAlerts||0} alerts; ${r.notifications?.length||0} notification(s) processed.`);}catch(e){showResult(out,e.message);}finally{b.disabled=false;}};const report=async(send)=>{const year=Number(document.getElementById('second-me-year').value),month=Number(document.getElementById('second-me-month').value),out=document.getElementById('second-me-report');showResult(out,'Working…');try{const r=await api(`/api/admin/second-me/${send?'monthly-report':'monthly-preview'}`,'POST',{year,month});showResult(out,send?`Report emailed to ${r.recipient}.`:(r.narrative||'No narrative returned.'));}catch(e){showResult(out,e.message);}};document.getElementById('second-me-preview').onclick=()=>report(false);document.getElementById('second-me-send').onclick=()=>report(true);}
function openPage(){document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page==='second_me'));const main=document.getElementById('main-content');if(!main)return;main.innerHTML='<div id="second-me-page"></div>';load();}
function install(){const nav=document.querySelector('.sidebar-nav');if(!nav||nav.querySelector('[data-page="second_me"]'))return;const item=document.createElement('div');item.className='nav-item';item.dataset.page='second_me';item.innerHTML='<span class="nav-icon">SM</span><span>Second Me</span>';item.addEventListener('click',openPage);nav.appendChild(item);}
window.SecondMeAdmin={load,openPage};install();new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});
})();
